frasesmain/apps/main/urls.py
from django.conf.urls import url
from .views import HomeView, CategoryDetail, PostDetail

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^(?P<slug>[-\w]+)/$', CategoryDetail.as_view(), name='category_detail'),
    url(r'^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/$', PostDetail.as_view(), name='post_detail'),
]

frasesmain/frasesmain/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.main.urls', namespace='main')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frasesmain/apps/main/models.py
from django.db import models
from django.template.defaultfilters import slugify
from ckeditor_uploader.fields import RichTextUploadingField

class Category(models.Model):

	name = models.CharField(max_length=50)
	slug = models.SlugField(unique=True, max_length=50)
	public = models.BooleanField(default=False)
	description = models.TextField(max_length=1000)
	seen = models.IntegerField(default=0)

	title_page = models.CharField(max_length=100)
	meta_description = models.TextField(max_length=155)

	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.name

class Author(models.Model):

	name = models.CharField(max_length=100)
	slug = models.SlugField(unique=True, editable=False, max_length=70)

	description = models.TextField(max_length=1000)

	def __str__(self):
		return self.name

	def save(self):
		self.slug = slugify(self.name)
		super(Author, self).save()


class Phrase(models.Model):

	category = models.ForeignKey(Category)
	author = models.ForeignKey(Author, null=True, blank=True)
	phrase = models.TextField(max_length=1000)

	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return "%s - %s" % (self.category, self.phrase)


class Post(models.Model):

	category = models.ForeignKey(Category)
	title = models.CharField(max_length=70)
	image = models.ImageField(upload_to='posts')
	slug = models.SlugField(unique=True, max_length=70)
	summary = RichTextUploadingField()

	phrases = models.ManyToManyField(Phrase, null=True, blank=True)

	content = RichTextUploadingField()

	meta_description = models.TextField(max_length=155)

	opengraph = models.ImageField(upload_to='opengraph', null=True, blank=True)
	twitter_card = models.ImageField(upload_to='twitter_card', null=True, blank=True)

	seen = models.BigIntegerField(default=0, null=True, blank=True)
	public = models.BooleanField(default=False)

	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title

	# def get_absolute_url(self):
	# 	return '/%s/%s/' % (self.category.slug, self.slug)

frasesmain/apps/main/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView

from .models import Category, Post

class HomeView(TemplateView):

	template_name = 'home.html'

	def get_context_data(self, **kwargs):
		context = super(HomeView, self).get_context_data(**kwargs)
		context['categories'] = Category.objects.filter(public=True).order_by('-created_at')
		context['posts'] = Post.objects.filter(public=True).order_by('-created_at')
		return context


class CategoryDetail(TemplateView):

	template_name = 'category_detail.html'

	def get_context_data(self, **kwargs):
		context = super(CategoryDetail, self).get_context_data(**kwargs)
		current_category = get_object_or_404(Category, slug=kwargs['slug'])
		current_category.seen += 1
		current_category.save()
		context['current_category'] = current_category
		context['categories'] = Category.objects.filter(public=True).order_by('-created_at')
		context['posts'] = Post.objects.filter(category=current_category, public=True).order_by('-created_at')
		return context

class PostDetail(TemplateView):

	template_name = 'detail.html'

	def get_context_data(self, **kwargs):
		context = super(PostDetail, self).get_context_data(**kwargs)
		category = get_object_or_404(Category, slug=kwargs['category'])
		post = get_object_or_404(Post, slug=kwargs['slug'], public=True)
		post.seen += 1
		post.save()
		context['category'] = category
		context['categories'] = Category.objects.filter(public=True).order_by('-created_at')
		context['post'] = post
		context['last_posts'] = Post.objects.filter(public=True).exclude(slug=post.slug).select_related('category').order_by('-created_at')[:6]
		context['phrases'] = post.phrases.all()
		return context

frasesmain/apps/main/templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="robots" content="NOODP">
	<!-- <meta name="google-site-verification" content="h7yoa13BwHe150thjALBy0qaM88KFFYjxizwcNcjSMY">
	<meta name="p:domain_verify" content="0441aecc95a44fc0a50185b9f228373b"/>-->
	{% block title %}
		
	{% endblock title %}
	<style>

		/* Style the links inside the navigation bar */
		.topnav a {
		    float: left;
		    display: block;
		    color: #f2f2f2;
		    text-align: center;
		    padding: .3em 1em;
		    text-decoration: none;
		    font-size: 14px;
		}

		/* Hide the link that should open and close the topnav on small screens */
		.topnav .icon {
		    display: none;
		}

		@media screen and (max-width: 800px) {
		  .topnav a {display: none;}
		  .topnav a.icon {
		    float: right;
		    display: block;
		  }
		}

		@media screen and (max-width: 800px) {
		  .topnav.responsive {
		  	position: absolute;
			background-color: #cd3232;
			width: 100%;
			top: 50px;
			left: 0;
			z-index: 1;
		  }

		  .topnav.responsive a {
		    float: none;
		    display: block;
		    padding: .7em 0;
		  }
		}
	</style>
	{% block styles %}
	{% endblock %}
</head>
<body>
	
	{% block content %}
		
	{% endblock content %}


	<footer class="footer">
		<div class="container">
			<div class="footer__content">
				<div class="same_width">
					<p class="footer__title">Frases de Amor</p>
					<p class="footer__paragraph">Las más románticas frases de amor para dedicar.</p>
				</div>
				<div class="same_width">
					<div>
						<p class="footer__title">Síguenos en nuestras redes sociales</p>
					</div>
					<div class="network-icon-list">
						<div><a target="_blank" href="https://www.facebook.com/pg/Frases-de-amor-para-dedicar-129739390969207/about/?ref=page_internal"><img class="facebook" src="{% static 'img/facebook-icon.png' %}?v1" alt="facebook"></a></div>
						<div><a target="_blank" href="https://twitter.com/frasesDamorr2"><img class="twitter" src="{% static 'img/twitter-icon.png' %}?v1" alt="twitter"></a></div>
						<div><a target="_blank" href="https://plus.google.com/u/0/104762153762212542255"><img class="google" src="{% static 'img/google-icon.png' %}?v1" alt="google"></a></div>
						<!--<div><a target="_blank" href="https://www.youtube.com/channel/UCnVA5n6CPQy9yg2IszGFx5A"><img class="youtube" src="{% static 'img/youtube-icon.png' %}?v1" alt="youtube"></a></div>-->
					</div>
				</div>
			</div>
		</div>
	</footer>

	{% if not debug %}
		<script>
		  /* Aquí va google analytics */
		</script>
	{% endif %}

	<div id="fb-root"></div>
	<script src="https://apis.google.com/js/platform.js" async defer>
	  {lang: 'es'}
	</script>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.9&appId=1666763640005297";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
	<script
	    type="text/javascript"
	    async defer
	    src="//assets.pinterest.com/js/pinit.js"
	></script>

	<script>
		function myFunction() {
		    var x = document.getElementById("myTopnav");
		    if (x.className === "topnav") {
		        x.className += " responsive";
		    	document.getElementById('icon').innerHTML = "&times;";
		    } else {
		        x.className = "topnav";
		    	document.getElementById('icon').innerHTML = "&#9776;";
		    }
		}
	</script>

	{% block scripts %}
	{% endblock scripts %}
</body>
</html>
<link rel="stylesheet" href="{% static 'css/main.css' %}?v1">
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/normalize.css' %}">

frasesmain/apps/main/templates/category_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load static from staticfiles %}

{% block title %}
	<title>{{ current_category.title_page }}</title>
	<meta name="description" content="{{ current_category.meta_description }}" />
	<meta name="title" content="{{ current_category.title_page }}" />
	<link rel="canonical" href="http://frasesdeamor.com.pe/{{ current_category.slug }}/">
{% endblock title %}

{% block styles %}
		<style>
		.slogan {
			text-align: center;
			padding: 1em 0;
			background: url("{% static 'img/home_banner.png' %}") no-repeat center; 
			background-size: cover;
		}

		/* Style the links inside the navigation bar */
		.topnav a {
		    float: left;
		    display: block;
		    color: #f2f2f2;
		    text-align: center;
		    padding: .3em 1em;
		    text-decoration: none;
		    font-size: 14px;
		}

		/* Hide the link that should open and close the topnav on small screens */
		.topnav .icon {
		    display: none;
		}

		@media screen and (max-width: 800px) {
		  .topnav a {display: none;}
		  .topnav a.icon {
		    float: right;
		    display: block;
		  }
		}

		@media screen and (max-width: 800px) {
		  .topnav.responsive {
		  	position: absolute;
			background-color: rgba(0, 0, 0, 0.80);
			width: 100%;
			top: 50px;
			left: 0;
			z-index: 1;
		  }

		  .topnav.responsive a {
		    float: none;
		    display: block;
		    padding: .7em 0;
		  }
		}
	</style>

{% endblock styles %}

{% block content %}
{{ block.super }}
	<section class="slogan">
		<header>
			<div class="container">
				<div class="row between">
					<div class="menu__main">
						<span class="menu__logo"><a href="{% url 'main:home' %}">Frases de Amor</a></span>
					</div>

					<div class="topnav" id="myTopnav">
					{% for category in categories %}
						<a href="{% url 'main:category_detail' category.slug %}">{{ category.name }}</a>
					{% endfor %}
					<a href="javascript:void(0);" class="icon" id="icon" onclick="myFunction()">&#9776;</a>
				</div>
				</div>
			</div>
		</header>

		<div class="container">
			<div class="row">
				<div class="home__header">
					<h1 class="slogan__title__h1">Frases de {{ current_category.name|lower }}</h1>
					<p class="slogan__description">{{ current_category.description }}</p>
				</div>
			</div>
		</div>
	</section>

	<section class="main_networks">
		<div class="container">
			<div class="row">
				<div class="networks_list column">
					<div class="networks_list__title">
						<p>Síguenos en nuestras redes sociales</p>
					</div>
					<div class="row">
						<div class="fb-like" data-href="https://www.facebook.com/Frases-de-amor-para-dedicar-129739390969207/" data-layout="button_count" data-action="like" data-size="large" data-show-faces="false" data-share="false"></div>
						<a href="https://twitter.com/frasesDamorr2" class="twitter-follow-button" data-show-count="false" data-size="large" data-show-screen-name="false">Follow @frasesDamorr2</a>
						<div class="g-plusone" data-annotation="none" data-href="https://plus.google.com/u/0/104762153762212542255"></div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="images">
		<div class="container">
			<div class="row page_content">
				<section class="left_side_category_detail">
					<div class="categories">
						<ul class="categories__list__detail">
							<li class="category__item">
								<a href="{% url 'main:home' %}">Inicio</a>
							</li>
							{% for category in categories %}
								{% if category.slug == current_category.slug %}
									<li class="category__item active">
										<a href="{% url 'main:category_detail' category.slug %}">{{ category.name }}</a>
									</li>
								{% else %}
									<li class="category__item">
										<a href="{% url 'main:category_detail' category.slug %}">{{ category.name }}</a>
									</li>
								{% endif %}
							{% endfor %}
						</ul>
					</div>
				</section>
				<section class="image_list">
					{% for post in posts %}
						<div class="image__item__detail">
							<a href="{% url 'main:post_detail' post.category.slug post.slug %}">
								{% thumbnail post.image "180" crop="center" as im %}
									<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" />
								{% endthumbnail %}
							</a>
							<div class="image__item__title__detail">
								<a href="{% url 'main:post_detail' post.category.slug post.slug %}">
									<p>{{ post.title }}</p>
								</a>
								<p class="post_description">
								{% with description=post.summary|safe %}
									{{ description|slice:"150" }}
								{% endwith %}
								</p>
							</div>
						</div>
					{% endfor %}
				</section>
				<section class="right_side">
					<div class="networks">
						<div class="fb-page" 
						  data-href="https://www.facebook.com/Frases-de-amor-para-dedicar-129739390969207/"
						  data-width="300" 
						  data-hide-cover="false"
						  data-show-facepile="false" 
						  data-show-posts="false"></div>
					</div>
				</section>
			</div>
		</div>
	</section>
{% endblock content %}

{% block scripts %}
	<script async src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script async src="{% static 'js/home.js' %}?v3"></script>
{% endblock scripts %}

frasesmain/apps/main/templates/detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load static from staticfiles %}

{% block title %}
	<title>{{ post.title }}</title>
	<meta name="title" content="{{ post.title }}">
	<meta name="description" content="{{ post.meta_description }}">
	<meta name="google" value="notranslate">
	<link rel="canonical" href="http://frasesdeamor.com.pe/{{ category.slug }}/{{ post.slug }}/">

	<!-- FACEBOOK -->
	<meta property="og:type" content="article">
	<meta property="og:site_name" content="FrasesDeAmor">
	<meta property="og:title" content="{{ post.title }}">
	<meta property="og:description" content="{{ post.meta_description }}">
	<meta property="og:url" content="http://frasesdeamor.com.pe/{{ category.slug }}/{{ post.slug }}">
	<meta property="og:image" content="{{ MEDIA_URL }}{{ post.opengraph }}">
	<meta property="og:image:width" content="1260">
	<meta property="og:image:height" content="630">

	<!-- TWITTER -->
	<meta name="twitter:card" content="summary_large_image">
	<meta name="twitter:site" content="@frasesDamorr2">
	<meta name="twitter:title" content="{{ post.title }}">
	<meta name="twitter:description" content="{{ post.meta_description }}">
	<meta name="twitter:image" content="{{ MEDIA_URL }}{{ post.twitter_card }}">

	<!-- google+ -->
	<meta itemprop="name" content="{{ post.title }}">
	<meta itemprop="description" content="{{ post.meta_description }}">
	<meta itemprop="image" content="{{ MEDIA_URL }}{{ post.twitter_card }}">

	<link href="https://fonts.googleapis.com/css?family=Kalam:300,400" rel="stylesheet">
{% endblock title %}

{% block styles %}
	<style>
		.phrase__image {
			text-align: center;
			background: url("{% static 'img/background_phrase.png' %}") no-repeat center; 
			background-size: cover;

			color: #fff;
			font-size: 1em;
			max-width: 350px;
			max-height: 350px;

			height: 256px;
			font-weight: 100;

			display: flex;
			align-items: center;
			justify-content: center;
			padding: 0 2em;
			font-family: 'Kalam', cursive;
			line-height: 2;
		}

		@media (min-width: 370px) {
			.phrase__image {
				height: 311px;
			}
		}
		@media (min-width: 400px) {
			.phrase__image {
				height: 350px;
			}
		}
	</style>
{% endblock styles %}


{% block content %}
	<header class="menu">
		<div class="container">
			<div class="row between">
				<div class="menu__main">
					<span class="menu__logo"><a href="{% url 'main:home' %}">Frases de Amor</a></span>
				</div>

				<div class="topnav" id="myTopnav">
					{% for category in categories %}
						<a href="{% url 'main:category_detail' category.slug %}">{{ category.name }}</a>
					{% endfor %}
					<a href="javascript:void(0);" class="icon" id="icon" onclick="myFunction()">&#9776;</a>
				</div>
			</div>
		</div>
	</header>

	<section class="main_networks hidden main_networks_postdetail">
		<div class="container">
			<div class="row">
				<div class="networks_list column">
					<div class="row">
						<div class="fb-share-button" data-href="http://frasesdeamor.com.pe/{{ category.slug }}/{{ post.slug }}/" data-layout="button_count" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse">Share</a></div>
						<a href="https://twitter.com/share" class="twitter-share-button" data-via="frasesDamorr2" data-size="large" data-hashtags="FrasesDeAmor">Tweet</a>
						<div class="g-plus" data-action="share" data-height="30"></div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<div class="main_page">
		<div class="container">
			<div class="row">
				<section class="left_side_detail">
					<div class="categories">
						<ul class="categories__list__detail">
							<li class="category__item">
								<a href="{% url 'main:home' %}">Inicio</a>
							</li>
							{% for category in categories %}
								<li class="category__item">
									<a href="{% url 'main:category_detail' category.slug %}">{{ category.name }}</a>
								</li>
							{% endfor %}
						</ul>
					</div>
				</section>
				<section class="main_side">
					<div class="article">
						<div class="container">
							<div>
								<div class="article__header border-bottom">
									<div class="article__title__wrap">
										<div class="article__category">
											<p>
												<a class="article__link" href="{% url 'main:home' %}">Frases de amor</a>
												<span class="article_text_secondary">></span>
												<a href="{% url 'main:category_detail' category.slug %}" class="article__link">{{ category.name }}</a>
											</p>
										</div>
										<div>
											<h1 class="article__title">{{ post.title }}</h1>
										</div>
									</div>
									<div class="row article__shares">
										<div class="fb-share-button" data-href="http://frasesdeamor.com.pe/{{ category.slug }}/{{ post.slug }}/" data-layout="button_count" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse">Share</a></div>
										<a href="https://twitter.com/share" class="twitter-share-button" data-via="frasesDeamorr2" data-size="large" data-hashtags="FrasesDeAmor">Tweet</a>
										<div class="g-plus" data-action="share" data-height="30" data-width="120"></div>
									</div>
								</div>
								<div class="summary">
									<p>{{ post.summary|safe }}</p>
								</div>
								<div class="phrase_list">
								{% for phrase in phrases %}
									<div class="phrase">
										<div class="phrase__image">
											<p>{{ phrase.phrase }}</p>
										</div>
										<div class="phrase__author">
											<p>Autor:</p>
											<p class="author__name">{{ phrase.author.name }}</p>
										</div>
									</div>
								{% endfor %}
								</div>
								<div class="article_content">
									<h2>{{ post.content|safe }}</h2>
								</div>
							</div>
						</div>
					</div>

					<div class="post_related">
						<div class="container">
							<div class="post_related__row">
								{% for post in last_posts %}
									<div class="post_related__image__item">
										<div class="post_related__image">
											{% thumbnail post.image "140" crop="center" as im %}
												<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" />
											{% endthumbnail %}
										</div>
										<div class="image__item__title">
											<a href="{% url 'main:post_detail' post.category.slug post.slug %}">
												<p>{{ post.title }}</p>
											</a>
										</div>
									</div>
								{% endfor %}
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>
	</div>
{% endblock content %}

{% block scripts %}
	<script async src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script async src="{% static 'js/home.js' %}?v1"></script>
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
{% endblock scripts %}

frasesmain/apps/main/templates/home.html
{% extends "base.html" %}
{% load thumbnail %}
{% load static from staticfiles %}
{% block title %}
	<title>Frases de amor, Frases de cumpleaños , Frases de amistad y mucho más</title>
	<meta name="description" content="Encuentra las mejores frases en un solo lugar: Frases de amor, Frases de amistad, Frases de cumpleaños y mucho más" />
	<meta name="google" value="notranslate" />
	<link rel="canonical" href="http://frasesdeamor.com.pe/">
{% endblock title %}

{% block styles %}
	<style>
		.slogan {
			text-align: center;
			padding: 1em 0;
			background: url("{% static 'img/home_banner.png' %}") no-repeat center; 
			background-size: cover;
		}

		/* Style the links inside the navigation bar */
		.topnav a {
		    float: left;
		    display: block;
		    color: #f2f2f2;
		    text-align: center;
		    padding: .3em 1em;
		    text-decoration: none;
		    font-size: 14px;
		}

		/* Hide the link that should open and close the topnav on small screens */
		.topnav .icon {
		    display: none;
		}

		@media screen and (max-width: 800px) {
		  .topnav a {display: none;}
		  .topnav a.icon {
		    float: right;
		    display: block;
		  }
		}

		@media screen and (max-width: 800px) {
		  .topnav.responsive {
		  	position: absolute;
			background-color: rgba(0, 0, 0, 0.80);
			width: 100%;
			top: 50px;
			left: 0;
			z-index: 1;
		  }

		  .topnav.responsive a {
		    float: none;
		    display: block;
		    padding: .7em 0;
		  }
		}
	</style>
{% endblock styles %}	

{% block content %}
	{{ block.super }}
	<section class="slogan">
		<header>
			<div class="container">
				<div class="row between">
					<div class="menu__main">
						<span class="menu__logo"><a href="{% url 'main:home' %}">Frases de Amor</a></span>
					</div>

					<div class="topnav" id="myTopnav">
					{% for category in categories %}
						<a href="{% url 'main:category_detail' category.slug %}">{{ category.name }}</a>
					{% endfor %}
					<a href="javascript:void(0);" class="icon" id="icon" onclick="myFunction()">&#9776;</a>
				</div>
				</div>
			</div>
		</header>

		<div class="container">
			<div class="row">
				<div class="home__header">
					<h1 class="slogan__title__h1">Frases de amor</h1>
					<p class="slogan__description">Encuentra las mejores frases en un solo lugar, frases de amor, frases de amistad, frases de desamor, frases de cumpleaños y muchas más</p>
				</div>
			</div>
		</div>
	</section>

	<section class="main_networks">
		<div class="container">
			<div class="row">
				<div class="networks_list column">
					<div class="networks_list__title">
						<p>Síguenos en nuestras redes sociales</p>
					</div>
					<div class="row">
						<div class="fb-like" data-href="https://www.facebook.com/Frases-de-amor-para-dedicar-129739390969207/" data-layout="button_count" data-action="like" data-size="large" data-show-faces="false" data-share="false"></div>
						<a href="https://twitter.com/frasesDamorr2" class="twitter-follow-button" data-show-count="false" data-size="large" data-show-screen-name="false">Follow @frasesDamorr2</a>
						<div class="g-plusone" data-annotation="none" data-href="https://plus.google.com/u/0/104762153762212542255"></div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="images">
		<div class="container">
			<div class="row page_content">
				<section class="left_side_category_detail">
					<div class="categories">
						<ul class="categories__list__detail">
							<li class="category__item">
								<a href="{% url 'main:home' %}">Inicio</a>
							</li>
							{% for category in categories %}
								<li class="category__item">
									<a href="{% url 'main:category_detail' category.slug %}">{{ category.name }}</a>
								</li>
							{% endfor %}
						</ul>
					</div>
				</section>
				<section class="image_list">
					{% for post in posts %}
						<div class="image__item__detail">
							<a href="{% url 'main:post_detail' post.category.slug post.slug %}">
								{% thumbnail post.image "180" crop="center" as im %}
									<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" />
								{% endthumbnail %}
							</a>
							<div class="image__item__title__detail">
								<a href="{% url 'main:post_detail' post.category.slug post.slug %}">
									<p>{{ post.title }}</p>
								</a>
								<p class="post_description">
								{% with description=post.summary|safe %}
									{{ description|slice:"150" }}
								{% endwith %}
								</p>
							</div>
						</div>
					{% endfor %}
				</section>
				<section class="right_side">
					<div class="networks">
						<div class="fb-page" 
						  data-href="https://www.facebook.com/Frases-de-amor-para-dedicar-129739390969207/"
						  data-width="300" 
						  data-hide-cover="false"
						  data-show-facepile="false" 
						  data-show-posts="false"></div>
					</div>
				</section>
			</div>
		</div>
	</section>
{% endblock content %}

{% block scripts %}
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="{% static 'js/home.js' %}?v1"></script>
{% endblock scripts %}

frasesmain/apps/main/templates/sitemap.html
<?xml version="1.0" encoding="UTF-8"?>
<urlset
  xmlns="https://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
{% spaceless %}
{% for url in urlset %}
  <url>
    <loc>{{ url.location }}</loc>
    {% if url.lastmod %}<lastmod>{{ url.lastmod|date:"Y-m-d" }}</lastmod>{% endif %}
    {% if url.changefreq %}<changefreq>{{ url.changefreq }}</changefreq>{% endif %}
    {% if url.priority %}<priority>{{ url.priority }}</priority>{% endif %}
    {% for image in url.item.images %}
      <image:image>
        <image:loc>{{ image.image.url }}</image:loc>
      </image:image>
    {% endfor %}
  </url>
{% endfor %}
{% endspaceless %}
</urlset>